<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export</name>
   <tag></tag>
   <elementGuidId>4fd5c50b-a591-4994-9e10-0286345ee2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.export-complaints</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdf6d570-cf2c-4388-9ff1-c276f9785e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>export-complaints</value>
      <webElementGuid>ae8add0e-f251-4970-bdb8-4aa8fdce9244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
      <webElementGuid>7677c8de-1bf6-43ed-86f8-96499485e129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;purple-theme&quot;]/app-root[1]/app-auth[1]/div[@class=&quot;auth&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;main&quot;]/app-complaints[1]/div[@class=&quot;complaints&quot;]/div[@class=&quot;title&quot;]/div[@class=&quot;filter&quot;]/div[@class=&quot;filter-btns&quot;]/button[@class=&quot;export-complaints&quot;]</value>
      <webElementGuid>bf96eb35-d03d-40de-9f71-535140a13af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5f9484a7-d29a-4e7d-8080-e134c262c4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Export' or . = 'Export')]</value>
      <webElementGuid>6af3ed37-3a8f-43b5-b891-b4950ccc3b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
