<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>dbd1234c-43fa-41e7-bb58-7a2c4688a38e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.login-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5585463f-6719-4879-a668-dbe364648a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-text</value>
      <webElementGuid>bf7d4897-adfb-4ae8-8115-d86daae08958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>801ca66c-1c5a-49b2-b39c-5743b6715b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;purple-theme&quot;]/app-root[1]/app-sign-in[1]/div[@class=&quot;sigin-container&quot;]/div[@class=&quot;login-input layout__row animate__animated animate__slideInLeft&quot;]/div[@class=&quot;sub-section&quot;]/button[@class=&quot;login-text&quot;]</value>
      <webElementGuid>80a8ed04-fb83-487e-9323-b2de0d25d36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6b7dbdfd-503c-45d5-9d78-3548b56ef283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>f3a64875-8a53-4823-bc18-c6870dfccff0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
