<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export</name>
   <tag></tag>
   <elementGuidId>33c68a8f-e102-4d3f-8967-e9b4856916ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.export-complaints</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cef457d-8c0d-4313-8deb-a7a2bfe76de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>export-complaints</value>
      <webElementGuid>ecc90d9a-5bda-4571-ad09-135159407771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
      <webElementGuid>3ec0034c-60f6-4f31-8f4d-89efcea6fa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;purple-theme&quot;]/app-root[1]/app-auth[1]/div[@class=&quot;auth&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;main&quot;]/app-complaints[1]/div[@class=&quot;complaints&quot;]/div[@class=&quot;title&quot;]/div[@class=&quot;filter&quot;]/div[@class=&quot;filter-btns&quot;]/button[@class=&quot;export-complaints&quot;]</value>
      <webElementGuid>4cf47a46-1534-4447-93b0-513dbe702782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>beb92369-5e8d-4bfe-a884-1ba69a633be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Export' or . = 'Export')]</value>
      <webElementGuid>085b4a95-866e-4290-a721-b278333e9ad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
