<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_One months</name>
   <tag></tag>
   <elementGuidId>98d757b7-1644-4160-a165-4e419a874bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.open-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-content']/div/div[2]/form/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c40d858d-99ca-4637-a9fc-b541d9abc31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open-status</value>
      <webElementGuid>d77372c8-fecf-46ba-b900-a9f27798b926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>One months</value>
      <webElementGuid>05fc118d-6df9-4fc3-ac15-9971ee332b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;export-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@id=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;custom-select&quot;]/div[@class=&quot;statuses&quot;]/div[@class=&quot;statuses-content&quot;]/div[@class=&quot;open-status&quot;]</value>
      <webElementGuid>c57ad8b0-b0d9-4bfb-9ee2-21800ee775d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content']/div/div[2]/form/div/div/div[2]/div/div</value>
      <webElementGuid>5280b633-8b7e-42d1-b58a-e2c775aa7373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div</value>
      <webElementGuid>7636d135-237c-44d3-9506-8d00dcbe27b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'One months' or . = 'One months')]</value>
      <webElementGuid>4cc8d7b1-b35f-478b-8cde-ac8898fb0b9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
