<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Date Range_custom-select</name>
   <tag></tag>
   <elementGuidId>c3f3ef09-944e-4822-afaa-0b95dbbbaeb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.custom-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-content']/div/div[2]/form/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40065384-cdb9-40c1-a350-da4a393bb776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>36284def-fac0-4a59-9733-4cfedfe8d56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;export-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@id=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;custom-select&quot;]</value>
      <webElementGuid>272f7624-5960-4dfe-8c6e-ade29b2bb60e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content']/div/div[2]/form/div/div</value>
      <webElementGuid>0da1cead-c798-456b-995e-6586813e6bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>c9196ceb-3422-4618-bfcb-bf217ea91561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
