<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your details to continue_signin-email</name>
   <tag></tag>
   <elementGuidId>f68621fa-2e3c-4e0e-885a-e8ed12c1171a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8af6235-3bae-4f11-ac9e-712e445b17df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>de7bdc3c-3d5e-495c-a35f-85962c3bf302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInEmail</value>
      <webElementGuid>263830ab-3cba-4035-a565-8374e1811944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email address</value>
      <webElementGuid>37f6c80a-a102-414f-aae5-64ccaaacd435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signin-email</value>
      <webElementGuid>a06c0e22-2ef5-4716-92e3-48c9c7d2eb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>24da8851-4c87-4491-9231-cbe4282276d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[^@]+@[^@]+\.[^@]+$</value>
      <webElementGuid>79c186f6-f6b8-45e3-8e9d-09071d0054c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout_input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f37d3249-0220-4bc0-aa13-026f913f0f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInEmail&quot;)</value>
      <webElementGuid>901ef2d6-c130-41af-af1b-0a68b7dfa9d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInEmail']</value>
      <webElementGuid>44807a9c-2d14-46ad-af2e-298e707fff27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6077846b-5ffb-4ffa-8dd0-2ef31d4e9ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'signInEmail' and @placeholder = 'Enter email address' and @name = 'signin-email']</value>
      <webElementGuid>8f16ca83-1a4b-43eb-abe6-ef2069266695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
