<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Complaints</name>
   <tag></tag>
   <elementGuidId>1fbcf47a-78d7-4aa6-838b-58e3906df22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.row.mb-2.sublinks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4820630a-10dd-4651-8e8a-7b88c6be6664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/feedback/complaints</value>
      <webElementGuid>8aaa3ee6-92c2-4965-b07c-cd8cf26e4f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row mb-2 sublinks</value>
      <webElementGuid>ab339418-e6d1-418a-accc-5ae0221fa490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8218f178-b566-47a8-a0fd-3c6e3a6e3843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complaints</value>
      <webElementGuid>9f5fc4b6-3950-49a0-86c5-ba3b931e95c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;purple-theme&quot;]/app-root[1]/app-auth[1]/div[@class=&quot;auth&quot;]/div[@class=&quot;sidebar showSideBar&quot;]/app-side-bar[1]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;items&quot;]/div[@class=&quot;nav-links&quot;]/div[@class=&quot;link-child ml-3&quot;]/span[@class=&quot;row mb-2 sublinks&quot;]</value>
      <webElementGuid>2eb71cc1-881a-4c17-bb58-152949566a89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>afee8eee-87b1-4991-9b05-3a00021d0881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Complaints' or . = 'Complaints')]</value>
      <webElementGuid>ae799d2f-0646-4a04-9757-0320ddba87b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
